runner: HIRLRunner

pipeline:
  name: "HIRL"
  num_cluster: [30000,10000,5000]
  train_emb: "vit_cls"
  num_neg_path: 100
  num_mlp_layer: 2
  activation: "relu"

T: 0.1
cluster_warmup_epoch: 40
iter_wise_assignment: False

base_runner: BEiTRunner

arch: "vit_base"
model: "beit_base"
patch_size: 16
num_classes: 8192
drop_path_rate: 0.1
init_values: 0.1

use_fp16: False
weight_decay: 0.05
weight_decay_end: 0.05
batch_size: 32
epochs: 400
warmup_epochs: 10
lr: 1.5e-3
min_lr: 1.0e-5
optimizer: adamw
accum_iter: 1
clip_grad: 3.0

data_path: "./datasets/Imagenet1K/ILSVRC/Data/CLS-LOC/"
output_dir: "./experiments/pretrain/hirl/beit_base_400eps/"

autoresume: True
resume: null
seed: 0
num_workers: 10

log_interval: 10
save_interval: 10

dist_url: "env://"
